name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Run tests
        run: make test

      - name: Generate quick schedule
        run: make run-heuristic-quick

      - name: Presubmit (strict)
        env:
          MAX_ADJ: '2'
          MAX_SAME_SLOT: '6'
        run: make presubmit-strict
        continue-on-error: true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ghis-artifacts
          if-no-files-found: warn
          path: |
            outputs/runs/latest/schedule.csv
            outputs/metrics.json
            outputs/validation.json
            outputs/audit.log

